name: cft
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - cuda-nvcc
  - jax
  - jaxlib=*=*cuda*
  - flax
  - optax
  - orbax-checkpoint
  - numpy
  - scipy
  - networkx
  - pymatgen
  - emmet-core
  - mp-api
  - tqdm
  - typing-extensions